In [1]:
#We import a library using the 'import' keyword as numpy's comma abbreviation is np
import numpy as np
import math

Array Creation

In [2]:
#Arrays are displayed as a list or list of lists and can be created through list as well. When creating an
# array, we pass in a list as an argument in nupy array
a= np.array([1,2,3])
print(a)
# We can print the number of dimension of a list using the ndim attribute
print(a.ndim)

[1 2 3]
1


In [3]:
# If we pass in a list of lists in numpy array, we create a multi-dimensional array, for instance, a matrix
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# We can print out the length of each dimension by calling the shape attribute, which return a tuple 
b.shape

(2, 3)

In [5]:
# We can also check the type of items in the array
a.dtype

dtype('int64')

In [6]:
# Besides integers, floats are also accepted in numpy arrays
c = np.array([2.2,5,1.1])
c.dtype.name

'float64'

In [7]:
# let's look at the data in your array
c

array([2.2, 5. , 1.1])

In [8]:
# Note that Numpy automatically converts integers, like 5, up to floats, since there is no less of prescision.
# Numpy will. try and give you the best data type format possible to keep your data types homogeneous, which 
# means all the same, in the array

In [11]:
# Sometimes we know the shape of an array that we want to create, but not what we want. to. be in it. Numpy
#offers sevral functions to create arrays with initial placeholders, such as zero's or one's
# let's create two arrays, both the same shape but with diffrent filler values
d = np.zeros ((2,3))
print(d)

e= np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# We can also generate an array with random numbers
np.random.rand(2,3)

array([[0.01767652, 0.09097694, 0.06725599],
       [0.68427038, 0.43268581, 0.90314371]])

In [13]:
# You'll see zeros, ones, and rand used quite often to create example arrays. especially in stack overflow
# posts and other forums.

In [14]:
# We can also create a sequence of numbers in an array with the arrange() function. The first argument is the 
# starting bound and the second argument is the ending bound, and the third argument is the diffrence between
# each consecutive numbers

# Les's create an array of every. number from ten(inclusive) to fifty (exclusive)
f= np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [15]:
# If we want to generate a sequence of floats, we can use the linspace() function. In this function the third 
# argument isn't the difference between two numbers, but the total number of items you want to. genrate 
np.linspace(0,2,15) #15 number from 0(inclusive)


array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

# Array Operations

In [16]:
# We can do many things on arrays, such as mathemetical manipulation (+,-,%,*)
# as well as use boolean arrays, which are. binary values. We can also do matrix manipulation such as
# product, transpose, inverse, and so forth.

In [17]:
# Arithmetic operaors on array apply elementwise.

# Let's create a couple of arrays
a = np.array([10,20,30,40])
b= np.array([1,2,3,4])

#Now let's look at a minus b
c=a-b
print(c)

# And let's look at a times b
d= a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [18]:
# With arithmetic manipulation, we can covert data to the way we want it to be.
#celcius to farenheit.

farenheit= np.array([1,-10,-20,-15,-5])

celcius= (farenheit - 31)*(5/9)
celcius

array([-16.66666667, -22.77777778, -28.33333333, -25.55555556,
       -20.        ])

In [19]:
# We can apply an operator on an array, and a boolean array will be 
# returned for element in the original. 
celcius > -20

array([ True, False, False, False, False])

In [20]:
celcius%2 ==0

array([False, False, False, False,  True])

In [21]:
#If we want elementwise product, we use the "*" sign
A= np.array([[1,1],[0,1]])
B= np.array([[2,0],[3,4]])
print(A*B)

# If we want to do matrix product, we use the '@' sign or use dot function
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [22]:
A.shape

(2, 2)

In [23]:
# Let's create an array of integers
array1= np.array([[1,2,3],[4,5,6]])
print(array1.dtype)

#Now let's create an array of floats
array2= np.array([[7.1,4.2,9.1],[10.4,3.2,12.3]])
print(array2.dtype)

int64
float64


In [24]:
# Let's do an addition for the two arrays
array3= array1+array2
print(array3)
print(array3.dtype)

[[ 8.1  6.2 12.1]
 [14.4  8.2 18.3]]
float64


In [25]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

67.3
18.3
6.2
11.216666666666667


In [28]:
#let's create an array with 15 elements with dimention of 3x5

b=np.arange(1,16,1).reshape(3,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


# Indexing, Slicing, and Iterating

# Indexing

In [32]:
# A one dimensional array, works in similar ways as a list to get an element in
# one-dimensional, we simply use the offset  index.
a= np.array([1,3,5,7])
a[2]

5

In [33]:
# let's create multidimensional array
a= np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
# integers the first being the row, and the seconf the column
a[2,0]

5

In [45]:
print(a[[0,1,2],[0,1,1]])

[1 4 6]


## Boolean Indexing

In [46]:
print(a>5)

[[False False]
 [False False]
 [False  True]]


In [47]:
print(a[a>5])

[6]


# Slicing

In [49]:
# Slicing is a way to create a sub-array based on the original array.
a=np.array([0,1,2,3,4,5])
print(a[:3])

[0 1 2]


In [50]:
print(a[2:4])

[2 3]


In [51]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
a[:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
a[:2,1:3]

array([[2, 3],
       [6, 7]])

In [54]:
# In multidimensional array, the first argument is for selecting rows, and the second
# argument is for selecting columns

In [56]:
sub_array = a[:2,1:3]
print("sub array index [0,0] value before change:",sub_array[0,0])
sub_array[0,0]=50
print("sub array index [0,0] value after change:",sub_array[0,0])
print("original array index [0,1] value after change:",a[0,1])

sub array index [0,0] value before change: 50
sub array index [0,0] value after change: 50
original array index [0,1] value after change: 50


# Trying Numpy with Datasets

In [58]:
wines= np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=1)
wines

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]])

In [59]:
# sol all rows combined but only the. first column from them would be
print("one integer 0 for slicing:",wines[:,0])
# But if. we wanted. the same values but wanted to. preserve. that they sit in their own rows we would write
print("0  to 1 for slicing: \n",wines[:,0:1])

one integer 0 for slicing: [7.4 7.8 7.8 ... 6.3 5.9 6. ]
0  to 1 for slicing: 
 [[7.4]
 [7.8]
 [7.8]
 ...
 [6.3]
 [5.9]
 [6. ]]


In [60]:
wines[:,0:3]

array([[7.4  , 0.7  , 0.   ],
       [7.8  , 0.88 , 0.   ],
       [7.8  , 0.76 , 0.04 ],
       ...,
       [6.3  , 0.51 , 0.13 ],
       [5.9  , 0.645, 0.12 ],
       [6.   , 0.31 , 0.47 ]])

In [61]:
#What if we want sevral non-consecutive columns
wines[:,[0,2,4]]

array([[7.4  , 0.   , 0.076],
       [7.8  , 0.   , 0.098],
       [7.8  , 0.04 , 0.092],
       ...,
       [6.3  , 0.13 , 0.076],
       [5.9  , 0.12 , 0.075],
       [6.   , 0.47 , 0.067]])

In [62]:
#nagative numbers mean slicing from back of the list.
wines[:,-1].mean()

5.6360225140712945